dist: trusty
sudo: false
# black list wip branches, however if pull requests are created for one then
# travis should build it
branches:
  except:
    - /^(wip|WIP)(-|_).*$/
language: node_js
node_js:
  - "12"
before_script:
  - bundle install --without development
  - npm install
  - make prepare-submodules
  # see: http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "time npm test"
env:
  global:
  - secure: "0vTh/6CdVgi1g9sHSCtiJuURDPNTgiX5eAu98W6UZhACVC3mLKG+DeBLY0U8PPlv9oK8pJggAwRQiUWdmc214tDk7ZkrHXx02S8EQgDL1Xy57wLhismlVJOFapMA1wkI/pCHADtc1ycYo6lYGhEDzGswjktxNImk2d9APYSrA4A="
  - secure: "A430lxRQcBORvdmn7a5EHW6ffPt+iO+KC5ZqvR/sCuh/SRJDrPvGgY5+D4T6xAAybwNLDddUdbxZ3ACUT7oUVFbRNEJzfLSo6ugkMeK+BnABckG4Bh9BEAI4xhqiune09qBDoxwpAKQBCXGKS5q06snabbkfLjx2H+yPqGHCsSE="
  - secure: "rnqygpeAbtFM1U82XMQgDMvXs+0ZiBLFNX38JXjPlXMDLNtoYzdb9uFnlEVIEuE7jj/SUt9DJCNgUdZG94nb8joQQ0LyvuFmDQphZ++ioTNcodk5lA3d4NyZ3mUtZURwwEnfJeZTJPPCw/8yz+zF/OIN1cknn61crj8N0Yp7cTo="
after_success: "time script/s3-deploy.sh"
