# whitelist
branches:
  only:
    - master
    - energy2d
notifications:
  irc: "irc.freenode.org#otrunk"
  email:
    recipients:
      - stephen.bannasch@gmail.com
      - sfentress@concord.org
      - rpk@pobox.com
      - janikpiotrek@gmail.com

language: node_js
node_js:
  - 0.8
before_script:
  - bundle install --binstubs
  - make clean; make
script: "make test"
