---
# environment can be 'development' or 'production'
# production:
#  - delivers minimized javascript resources
#  - sets JavaScript variable: Lab.config.environment = 'production'
# development:
#  - delivers un-minimized javascript resources
#  - sets JavaScript variable: Lab.config.environment = 'development'
#  - enables rack-livereload
:environment: development
:server:
  development:
    :hostname: localhost:9292
  production:
    :hostname: lab.concord.org
:jsconfig:
  # This can be set optionally set to true to disable links to DataGames and Java models
  # Can even be done dynamically: LAB_STATIC=true ./script/generate-js-config.rb
  :static: false
  :sharing: true
  :logging: true
  :tracing: false
  :home: http://lab.concord.org
  # Set :homeForSharing to the host where shared Interactives are found
  # if you don't want to share the ones on the actual server.
  # Example if you host the Interactives on a static S3 site and want the
  # sharing links to point to the same Interactives at http://lab.concord.org
  :homeForSharing:
  :homeInteractivePath: /interactives.html
  :homeEmbeddablePath: /embeddable.html
  :benchmarkAPIurl: https://script.google.com/macros/s/AKfycbzosXAVPdVRFUrF6FRI42dzQb2IGLnF9GlIbj9gUpeWpXALKgM/exec
  :actualRoot: ""
  :utmCampaign:
  :fontface: Lato
  # used as the basis for urls that lock in the Lab engine, should be blank
  # everywhere other than production I think:
  :versioned_home: http://lab.concord.org/version/
:google_analytics:
  :account_id:
# password and alias for Java siging certificate.
:java:
  :password: abc123
  :alias: lab-sample-keystore
  :keystore_path: config/lab-sample-keystore.jks
# deploy configuration for working with Amazon Web Services
:deploy:
  :targets:
  - :name: lab
    :url: lab.concord.org
    :branch: production
  - :name: lab-staging
    :url: lab-staging.concord.org
    :branch: staging
  - :name: lab-dev
    :url: lab.dev.concord.org
    :branch: master
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev/
  - :name: lab2-dev
    :url: lab2.dev.concord.org
    :branch: inquiry-space
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev2/
  - :name: lab3-dev
    :url: lab3.dev.concord.org
    :branch: master
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev3/
  :group_name: lab.dev
  :zone_domain: concord.org.
  :zone_records_name: dev.concord.org
  :pem:
    :name: lab-dev
    :path: ~/.ec2
