---
:server:
  development:
    :hostname: localhost:9292
  production:
    :hostname: lab.concord.org
:google_analytics:
  :account_id:
# password and alias for Java siging certificate.
:java:
  :password: abc123
  :alias: lab-sample-keystore
  :keystore_path: config/lab-sample-keystore.jks
# deploy configuration for working with Amazon Web Services
:deploy:
  :targets:
  - :name: lab
    :url: lab.concord.org
    :branch: production
  - :name: lab-staging
    :url: lab-staging.concord.org
    :branch: staging
  - :name: lab-dev
    :url: lab.dev.concord.org
    :branch: master
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev/
  - :name: lab2-dev
    :url: lab2.dev.concord.org
    :branch: inquiry-space
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev2/
  - :name: lab3-dev
    :url: lab3.dev.concord.org
    :branch: master
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev3/
  :group_name: lab.dev
  :zone_domain: concord.org.
  :zone_records_name: dev.concord.org
  :pem:
    :name: lab-dev
    :path: ~/.ec2
